/*
 * This file is generated by jOOQ.
 */
package com.tiddar.nettylearn.stdchat.model.chat;


import com.tiddar.nettylearn.stdchat.model.DefaultCatalog;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chat extends SchemaImpl {

    private static final long serialVersionUID = 1871801688;

    /**
     * The reference instance of <code>chat</code>
     */
    public static final Chat CHAT = new Chat();

    /**
     * The table <code>chat.chat</code>.
     */
    public final com.tiddar.nettylearn.stdchat.model.chat.tables.Chat CHAT_ = com.tiddar.nettylearn.stdchat.model.chat.tables.Chat.CHAT_;

    /**
     * No further instances allowed
     */
    private Chat() {
        super("chat", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            com.tiddar.nettylearn.stdchat.model.chat.tables.Chat.CHAT_);
    }
}
