/*
 * This file is generated by jOOQ.
 */
package com.tiddar.nettylearn.stdchat.model.chat;


import com.tiddar.nettylearn.stdchat.model.chat.tables.Chat;
import com.tiddar.nettylearn.stdchat.model.chat.tables.records.ChatRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.ULong;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>chat</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ChatRecord, ULong> IDENTITY_CHAT_ = Identities0.IDENTITY_CHAT_;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> KEY_CHAT_PRIMARY = UniqueKeys0.KEY_CHAT_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ChatRecord, ULong> IDENTITY_CHAT_ = Internal.createIdentity(com.tiddar.nettylearn.stdchat.model.chat.tables.Chat.CHAT_, com.tiddar.nettylearn.stdchat.model.chat.tables.Chat.CHAT_.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ChatRecord> KEY_CHAT_PRIMARY = Internal.createUniqueKey(com.tiddar.nettylearn.stdchat.model.chat.tables.Chat.CHAT_, "KEY_chat_PRIMARY", Chat.CHAT_.ID);
    }
}
