/*
 * This file is generated by jOOQ.
 */
package com.tiddar.nettylearn.stdchat.model.chat;


import com.tiddar.nettylearn.stdchat.model.chat.tables.Chat;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in chat
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>chat.chat</code>.
     */
    public static final Chat CHAT_ = Chat.CHAT_;
}
